### ISSUE TITLE
Automatically pre-fill the file path in code running with loaded/saved file

### ISSUE THREAD

**Issue by jwijenbergh** [bornobob/Notepad--#24]
When we load/save a file, we can automatically save the file path and pre-fill it in the code running modal.

**Comment by Justin-Reniers** [comment]
We adjusted the way running code works. The path of a file no longer needs to be given, only the language. Instead, we now take the text in the current editor (hence it should use the text in the current tab), and run that instead. This limits functionality a tiny bit in the sense that using multi-file code is not supported for running which we could do previously, but this works more nicely with quickly trying to run the code in the editor tab.
