### ISSUE TITLE
Star in tab does not get removed on save of tab

### ISSUE THREAD

**Issue by Justin-Reniers** [bornobob/Notepad--#36]

**Comment by jwijenbergh** [comment]
For me this happens when I'm trying to save a tab that previously had saved text, but now the text field is empty. Is there any other scenario where you encountered this?

**Comment by jwijenbergh** [comment]
Please test `1825df7`, it seems to work in every scenario that I've tested now. It did not only happen when there is empty text but also if the text is the same as the previous text.

**Comment by Justin-Reniers** [comment]
> For me this happens when I'm trying to save a tab that previously had saved text, but now the text field is empty. Is there any other scenario where you encountered this?

This also happened to me whenever I added text, and removed exactly that text and then try to save it: the modal that says the tab has been saved pops up, but the star remains. The modal also keeps popping up in the same fashion as our saved modal initially did.

**Comment by Justin-Reniers** [comment]
> Please test [1825df7](https://github.com/bornobob/Notepad--/commit/1825df7ca6c29b52c5676e87685def2a2b8707ea), it seems to work in every scenario that I've tested now. It did not only happen when there is empty text but also if the text is the same as the previous text.

It still does not seem to work for me. The star persists, and if I try to save an empty tab, the modal does not pop up at all.

**Comment by jwijenbergh** [comment]
> > Please test [1825df7](https://github.com/bornobob/Notepad--/commit/1825df7ca6c29b52c5676e87685def2a2b8707ea), it seems to work in every scenario that I've tested now. It did not only happen when there is empty text but also if the text is the same as the previous text.
> 
> It still does not seem to work for me. The star persists, and if I try to save an empty tab, the modal does not pop up at all.
> Edit - It might be just on my browser? Some of the bugs that we seemed to have only really happened on my browser, it would be great if either @bornobob or @huynguy97 could also test this fix.

Did you have syntax highlighting disabled? I see that syntax highlighting makes it so that isSaved is updated more frequently. Will post a new commit for you to try

**Comment by jwijenbergh** [comment]
Please test 4cc52c7 and make a gif if the issue persists.

**Comment by jwijenbergh** [comment]
> > For me this happens when I'm trying to save a tab that previously had saved text, but now the text field is empty. Is there any other scenario where you encountered this?
> 
> This also happened to me whenever I added text, and removed exactly that text and then try to save it: the modal that says the tab has been saved pops up, but the star remains. The modal also keeps popping up in the same fashion as our saved modal initially did.

However, this is really weird as this should never happen. The function that calls the modal also calls the setTitle function, can you test it in a private window? It might be that something is messing up in your cache

**Comment by jwijenbergh** [comment]
When I load a file, save it, reload the page and then delete the contents of the tab and then try to save it indeed still doesn't work. Will debug this

**Comment by Justin-Reniers** [comment]
> > It still does not seem to work for me. The star persists, and if I try to save an empty tab, the modal does not pop up at all.
> > Edit - It might be just on my browser? Some of the bugs that we seemed to have only really happened on my browser, it would be great if either @bornobob or @huynguy97 could also test this fix.
> 
> Did you have syntax highlighting disabled? I see that syntax highlighting makes it so that isSaved is updated more frequently (we need to remove this code). Will post a new commit for you to try. New empty tabs are automatically saved btw, you can only save when there is a * in the title.
> 
> > This also happened to me whenever I added text, and removed exactly that text and then try to save it: the modal that says the tab has been saved pops up, but the star remains. The modal also keeps popping up in the same fashion as our saved modal initially did.
> 
> However, this is really weird as this should never happen. The function that calls the modal also calls the setTitle function (and the conditions of that should be satisfied to remove the star), can you test it in a private window? It might be that something is messing up in your cache
> 
> Anyways, test [4cc52c7](https://github.com/bornobob/Notepad--/commit/4cc52c72b68e168cfb0242cd5d4a3d738a40c243) in a clean browser

It's super nice! This works in a clean browser indeed. I'm going to clear out the cache of my browser, but I've verified that it works.

**Comment by Justin-Reniers** [comment]
> When I load a file, save it, reload the page and then delete the contents of the tab and then try to save it indeed still doesn't work. Will debug this.
> 
> Another commit... [454e9a6](https://github.com/bornobob/Notepad--/commit/454e9a6fc9bb860279a7b41355eec7cbabbd3a0c), fixes this issue for me.

This also works for me! With that, I think all the bugs have been resolved as far as my manual testing has shown. I think we can close the issue for now. Good work!
