### ISSUE TITLE
Find a way to accurately choose two tabs to diff

### ISSUE THREAD

**Issue by huynguy97** [bornobob/Notepad--#43]
Currently theres a bug when you add tabs, remove tabs and then try to diff. This is because our tab implementation.

_Originally posted by @huynguy97 in https://github.com/bornobob/Notepad--/issues/42#issuecomment-738983831_

**Comment by jwijenbergh** [comment]
It's because you're using ids of tabs in diff, I have already discussed with you why this is not a good solution. This is not a problem with the tabs implementation as I chose not to reset ids (that will have a performance penalty).

**Comment by huynguy97** [comment]
Fixed many bugs so far. Getting current editor data works, between tabs 1-2 works as well even if you click another tab.
