### ISSUE TITLE
Implement more efficient syntax highlighting by only updating when needed

### ISSUE THREAD

**Issue by jwijenbergh** [bornobob/Notepad--#5]
Right now we're updating the highlighting on every key press (or after when a request was already being processed). 

A more efficient way would be to update it on e.g. every new word added. We would thus need to do the following:

1. Update the html tree with the added text at the exact cursor point (this means that when a full word hasn't been completed yet, it will simply be the normal color but the code that was already added is still highlighted)
2. Send the updated text to the syntax highlighter in python after a new word has been added

Nr 1. is the culprit here, need to find good practices how to do this

**Comment by jwijenbergh** [comment]
I think this feature is simply too difficult to implement efficiently. Should we close this? @bornobob

**Comment by bornobob** [comment]
Agreed
